### PR TITLE
Add perl-Net-HTTPS-NB and perl-HTTP-Async into xcat-dep

### PR DESCRIPTION
**Pull request by zet809**

### CODE REVIEW

**Comment by daniceexi** [comment]
I am OK with the change and agree to merge.

**Comment by daniceexi** [comment]
Please update the new dep packages to GSA server and trigger a new deb tar.

**Comment by whowutwut** [comment]
When the files are there, I can kick off the deps build.  Should we target Thursday 3/24 build to sync with the weekly build?

**Comment by daniceexi** [comment]
Yes, we want to make the dep for docker support to be ready ASAP. I think @zet809 can put in the dep packages today.

**Comment by zet809** [comment]
I have upload both the rpm package and deb package onto GSA.

**Comment by daniceexi** [comment]
@whowutwut Will the new dep tar be updated to the xcat.org directly?

**Comment by whowutwut** [comment]
@daniceexi  Yes would rebuild xcat-deps for Linux and Ubuntu.  @tingtli  emailed me and said she would respin the deps package.  If you want me to do it, let me know. I would target it for after the daily build on Thurs which is updated to xcat.org so we are in sync.

**Comment by whowutwut** [comment]
@zet809 can you update the README in the GSA directory with the changes?

**Comment by zet809** [comment]
@whowutwut I have updated the README before you adding ipmitool-xcat for RHEL7 ppc64 and SLES12 ppc64le.
For the comments you added, the date is 22 Feb 2016, shall it  be 22 Mar 2016 or I am wrong?

**Pull request merged**
