### PR TITLE
Support for EL9

### PR DESCRIPTION
**Pull request by Obihoernchen**
The following changes allow xCAT to be compatible with EL9 based OSs.

Also add support for Rocky Linux and AlmaLinux 8/9.

Note: The RPM signing key is still an issue on other packages. See: https://github.com/xcat2/xcat-dep/issues/51
For testing purposes you may remove the key with: `rpmsign --delsign <rpm>`

### CODE REVIEW

**Comment by gurevichmark** [comment]
@Obihoernchen 
Thank you for this contribution. With your changes I was able to rebuild and install `perl-Net-Telnet`, `perl-HTML-Form` and `ipmitool-xcat` on RHEL9 . But I am having problems rebuilding `perl-IO-Stty`:
```
[root@vm-170 perl-IO-Stty]# rpmbuild --rebuild perl-IO-Stty-0.04-5.fc34.src.rpm
Installing perl-IO-Stty-0.04-5.fc34.src.rpm
warning: user mockbuild does not exist - using root
warning: group mock does not exist - using root
warning: user mockbuild does not exist - using root
warning: group mock does not exist - using root
warning: user mockbuild does not exist - using root
warning: group mock does not exist - using root
setting SOURCE_DATE_EPOCH=1611705600
error: Failed build dependencies:
        perl(Pod::Coverage) >= 0.18 is needed by perl-IO-Stty-0.04-5.el9.noarch
[root@vm-170 perl-IO-Stty]#
```
I can not find the RPM that provides `Pod::Coverage` ?

**Comment by Obihoernchen** [comment]
@gurevichmark sorry forgot to post the prerequisites:

It's from CRB repo:

```
perl-Pod-Coverage.noarch                    0.23-25.el9                      @crb               
```

For Alma/Rocky it's:

```
dnf config-manager --set-enabled crb
dnf install epel-release
dnf install perl-ExtUtils-MakeMaker perl-Pod-Coverage perl-Test perl-Test-Simple ncurses-devel readline-devel OpenIPMI-devel perl-HTML-Parser perl-HTTP-Message gnu-efi gnu-efi-devel perl nasm golang
```

For RHEL you need to enable CRB via subscription-manager.

**Comment by gurevichmark** [comment]
@Obihoernchen Thanks. With those prereqs I can now rebuild and install `perl-IO-Stty`

**Review by besawn — CHANGES_REQUESTED** [review]
@Obihoernchen Thank you for the contribution. I have a few requests.

1.) The version of `perl-IO-Stty-0.04-5.fc34.src.rpm` included in this pull request is unsigned:
```
rpm -qpi perl-IO-Stty/perl-IO-Stty-0.04-5.fc34.src.rpm | grep Signature
Signature   : (none)
```

but the the version available from fedoraproject.org (https://dl.fedoraproject.org/pub/fedora/linux/releases/34/Everything/source/tree/Packages/p/perl-IO-Stty-0.04-5.fc34.src.rpm) is signed:
```
rpm -qpi perl-IO-Stty-0.04-5.fc34.src.rpm | grep Signature
Signature   : RSA/SHA256, Wed 27 Jan 2021 08:30:38 PM EST, Key ID 1161ae6945719a39
```
The other source rpms in this pull request are also signed. Could you please update this pull request to include the signed version of `perl-IO-Stty-0.04-5.fc34.src.rpm`?

2.) Can you provide some more information about the ipmitool patches?

What process did you use to arrive at this set of patches?

What hardware platforms did you test the changes on?

Are these included to fix specific problems you have encountered?

Can you provide some additional explanation of your thought process with these patches?

**Comment by Obihoernchen** [comment]
Hi @besawn 

1.)
sure. I don't know why the RPM in this PR is unsigned. Probably because of some testing because of https://github.com/xcat2/xcat-dep/issues/51
It's fixed now.

2.)
I just used the latest EL9 ipmitool package and merged all patches.

So far I did tests on x86 and aarch64. But not in depth tests with fw updates etc. Just common stuff like rpower, rvitals, rinv.

No I didn't hit any issues. I had to rebuild the package for EL9 anyway, so I thought I could include the latest security fixes.
That was pretty much all I was thinking about ;)

**Comment by besawn** [comment]
@Obihoernchen Thanks for following up and thanks again for the contribution!

**Review by besawn — APPROVED** [review]

**Pull request merged**
